"""应用级常量与主题配置。"""
from pathlib import Path

APP_NAME = "JY 临时需求工具箱"
CONFIG_DIR = Path.home() / ".jy_toolbox"
CONFIG_FILE = CONFIG_DIR / "config.json"

COLOR_BG = "#eef1f4"
COLOR_SURFACE = "#f8f9fa"
COLOR_SURFACE_RAISED = "#f3f4f6"
COLOR_FIELD = "#fbfcfd"
COLOR_PRIMARY = "#2da44e"
COLOR_PRIMARY_DARK = "#1f7a3d"
COLOR_PRIMARY_HOVER = "#279247"
COLOR_PRIMARY_PRESSED = "#1f7a3d"
COLOR_TEXT = "#24292f"
COLOR_MUTED = "#57606a"
COLOR_DISABLED = "#8c959f"
COLOR_BORDER = "#d0d7de"
COLOR_BORDER_LIGHT = "#8c959f"
COLOR_ACCENT = "#eaf7ef"
COLOR_ACCENT_TEXT = "#1a7f37"
COLOR_INFO_BLUE = "#0969da"
COLOR_BUTTON = "#f8f9fa"
COLOR_BUTTON_HOVER = "#eef1f4"
COLOR_BUTTON_PRESSED = "#e2e7ec"
COLOR_DANGER = "#cf222e"
COLOR_DANGER_DARK = "#a40e26"
COLOR_DANGER_HOVER = "#a40e26"
COLOR_DANGER_PRESSED = "#82071e"
COLOR_WARNING = "#bf8700"
COLOR_WARNING_DARK = "#9a6700"
COLOR_WARNING_PRESSED = "#7d4e00"
COLOR_TOOL_SELECTED = COLOR_PRIMARY
COLOR_TOOL_UNSELECTED = COLOR_BUTTON
APP_FONT = ("Microsoft YaHei UI", 9)
APP_FONT_BOLD = ("Microsoft YaHei UI", 9, "bold")
APP_FONT_SMALL = ("Microsoft YaHei UI", 8)
BUTTON_RADIUS = 5
